version: "3.9"

services:
  terraform:
    image: hashicorp/terraform:1.6
    container_name: terraform
    working_dir: /infra
    volumes:
      - ./terraform:/infra
    entrypoint: [ "terraform" ]
